### ISSUE TITLE
Problème "development mode" avec Vue.js en production...

### ISSUE THREAD

**Issue by HapLifeMan** [Grafikart/Front-end-boilerplate#20]
Je rencontre un petit problème en production avec Vue.js...
Aucun problème lorsque je lance la commande `npm run dev` et `npm run build` mais j'ai un warning (en production) dans la console qui me dit :

https://puu.sh/ta2sB/cddf5d56ed.png

J'ai bien entendu cherché pendant des heures sur Google, il y avait plein de solutions (le flag -p de webpack pour la production, l'environnement etc...) mais aucunes n'étaient concluantes, alors si vous pouvez aider... Ça sera avec grand plaisir :)

La commande derrière "npm run build" :
`NODE_ENV=production rm -rf public/assets/*.* && webpack -p --config resources/assets/build/webpack.prod.js`

**Comment by MatthieuMota** [comment]
Avec Webpack, il faut que tu injectes la variable d'environnement process.env.NODE_ENV grâce au DefinePlugin. Grâce à ça, il va compiler Vue JS en production :) si tu veux plus d'infos https://vuejs.org/v2/guide/deployment.html#With-Build-Tools

```
var webpack = require('webpack')
var env = '"production"'
module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: env
      }
    })
  ]
}
```

Attention aux guillemets, ils sont importants ;)

**Comment by Grafikart** [comment]
Jvais modifier ça

**Comment by HapLifeMan** [comment]
Autre solution : https://www.grafikart.fr/forum/topics/25050 :)

**Comment by Grafikart** [comment]
J'ai au final retiré Vue car je ne l'utilise pas dans tous les projets.
