### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Flolax** [Grafikart/Front-end-boilerplate#5]
Bonjour,

J'ai tenté par tous les moyens que j'ai pu trouver sur internet de pouvoir utiliser des fichiers php avec front-end-boilerplate mais une erreur se produit : 

Cannot GET /

J'utilise wamp et front-end-boilerplate, une idée ?

**Comment by Grafikart** [comment]
Edite ce fichier https://github.com/Grafikart/Front-end-boilerplate/blob/master/gulpfile.coffee
Et décommente la partie proxy pour mettre l'url de ton application sur Wamp

**Comment by Flolax** [comment]
Grand merci :)
