### ISSUE TITLE
Bug proxy bypass

### ISSUE THREAD

**Issue by ptitbibice** [Grafikart/Front-end-boilerplate#8]
Hi,

thanks for your tuto, it's great.
I try to use the proxy bypass, but in your code, req.url is a string, so there is no method 'includes'.
Can you fix this plz,

thanks, best regards

**Comment by Grafikart** [comment]
I'm currently thinking about removing proxy from my configuration since it's quite buggy. So I have no plan to extend this feature :(

I prefer using my default web server to test my site and load assets using the web server generated by npm run dev

**Comment by Grafikart** [comment]
Proxy removed ;)
